version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:49"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: "daily"

